version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /1password/onepassword_sdks/demo-inventory-tracker-webapp
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7

  - package-ecosystem: npm
    directory: /1password/onepassword_sdks/demo-vault-backup-webapp
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7

  - package-ecosystem: npm
    directory: /1password/onepassword_sdks/demo-vault-migration-webapp
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7

  - package-ecosystem: gomod
    directory: /1password/reporting/beta/golang-lambda-deployment
    schedule:
      interval: weekly
      day: monday
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
