services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/webapp
    environment:
      - NODE_ENV=development
    command: npm start