services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: demo-vault-migration-webapp:v1.0.2
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    command: npm start

